//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BikeStation", Namespace="http://schemas.datacontract.org/2004/07/ProxyCache.Models")]
    [System.SerializableAttribute()]
    public partial class BikeStation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AvailableBikesk__BackingFieldField;
        
        private int BikeStandsk__BackingFieldField;
        
        private double Latitudek__BackingFieldField;
        
        private double Longitudek__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AvailableBikes>k__BackingField", IsRequired=true)]
        public int AvailableBikesk__BackingField {
            get {
                return this.AvailableBikesk__BackingFieldField;
            }
            set {
                if ((this.AvailableBikesk__BackingFieldField.Equals(value) != true)) {
                    this.AvailableBikesk__BackingFieldField = value;
                    this.RaisePropertyChanged("AvailableBikesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BikeStands>k__BackingField", IsRequired=true)]
        public int BikeStandsk__BackingField {
            get {
                return this.BikeStandsk__BackingFieldField;
            }
            set {
                if ((this.BikeStandsk__BackingFieldField.Equals(value) != true)) {
                    this.BikeStandsk__BackingFieldField = value;
                    this.RaisePropertyChanged("BikeStandsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Latitude>k__BackingField", IsRequired=true)]
        public double Latitudek__BackingField {
            get {
                return this.Latitudek__BackingFieldField;
            }
            set {
                if ((this.Latitudek__BackingFieldField.Equals(value) != true)) {
                    this.Latitudek__BackingFieldField = value;
                    this.RaisePropertyChanged("Latitudek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Longitude>k__BackingField", IsRequired=true)]
        public double Longitudek__BackingField {
            get {
                return this.Longitudek__BackingFieldField;
            }
            set {
                if ((this.Longitudek__BackingFieldField.Equals(value) != true)) {
                    this.Longitudek__BackingFieldField = value;
                    this.RaisePropertyChanged("Longitudek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProxyCache")]
    public interface IProxyCache {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/GetStations", ReplyAction="http://tempuri.org/IProxyCache/GetStationsResponse")]
        RoutingService.ServiceReference1.BikeStation[] GetStations(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/GetStations", ReplyAction="http://tempuri.org/IProxyCache/GetStationsResponse")]
        System.Threading.Tasks.Task<RoutingService.ServiceReference1.BikeStation[]> GetStationsAsync(string city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyCacheChannel : RoutingService.ServiceReference1.IProxyCache, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyCacheClient : System.ServiceModel.ClientBase<RoutingService.ServiceReference1.IProxyCache>, RoutingService.ServiceReference1.IProxyCache {
        
        public ProxyCacheClient() {
        }
        
        public ProxyCacheClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyCacheClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RoutingService.ServiceReference1.BikeStation[] GetStations(string city) {
            return base.Channel.GetStations(city);
        }
        
        public System.Threading.Tasks.Task<RoutingService.ServiceReference1.BikeStation[]> GetStationsAsync(string city) {
            return base.Channel.GetStationsAsync(city);
        }
    }
}
